//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawsVN.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LawsVN.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tài khoản.
        /// </summary>
        public static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản.
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác thực.
        /// </summary>
        public static string Accuracy {
            get {
                return ResourceManager.GetString("Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu văn bản quan tâm thành công..
        /// </summary>
        public static string AddDocumentOfInterestToSuccess {
            get {
                return ResourceManager.GetString("AddDocumentOfInterestToSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm nâng cao.
        /// </summary>
        public static string AdvancedSearch {
            get {
                return ResourceManager.GetString("AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả nội dung.
        /// </summary>
        public static string AllContent {
            get {
                return ResourceManager.GetString("AllContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả lĩnh vực.
        /// </summary>
        public static string AllFields {
            get {
                return ResourceManager.GetString("AllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp hết hiệu lực.
        /// </summary>
        public static string AlmostOutOfDate {
            get {
                return ResourceManager.GetString("AlmostOutOfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp sửa đổi .
        /// </summary>
        public static string Altering {
            get {
                return ResourceManager.GetString("Altering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áp dụng.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ApplyEn {
            get {
                return ResourceManager.GetString("ApplyEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin xem nhiều.
        /// </summary>
        public static string ArticlesMostView {
            get {
                return ResourceManager.GetString("ArticlesMostView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthorizeAttribute không áp dụng trong Cache ChildAction.
        /// </summary>
        public static string AuthorizeAttributeCannotUseWithinChildActionCache {
            get {
                return ResourceManager.GetString("AuthorizeAttributeCannotUseWithinChildActionCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model cơ sở chưa được khởi tạo.
        /// </summary>
        public static string BaseModelNull {
            get {
                return ResourceManager.GetString("BaseModelNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cả hai.
        /// </summary>
        public static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin doanh nghiệp.
        /// </summary>
        public static string BusinessInformation {
            get {
                return ResourceManager.GetString("BusinessInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa lĩnh vực quan tâm duy nhất.
        /// </summary>
        public static string CanNotDeleteSingleFieldOfInterest {
            get {
                return ResourceManager.GetString("CanNotDeleteSingleFieldOfInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp có hiệu lực.
        /// </summary>
        public static string ComingIntoEffect {
            get {
                return ResourceManager.GetString("ComingIntoEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu xác nhận.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu không khớp.
        /// </summary>
        public static string ConfirmPasswordNotMatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quy ước và bảo mật.
        /// </summary>
        public static string ConventionsAndPrivacy {
            get {
                return ResourceManager.GetString("ConventionsAndPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu hiện tại.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng nói về chúng tôi.
        /// </summary>
        public static string CustomersTalkAboutUs {
            get {
                return ResourceManager.GetString("CustomersTalkAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Văn bản pháp luật.
        /// </summary>
        public static string CustomersVBPL {
            get {
                return ResourceManager.GetString("CustomersVBPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian lọc từ ngày không đúng dạng: ngày/tháng/năm.
        /// </summary>
        public static string DateFromInvalidDataType {
            get {
                return ResourceManager.GetString("DateFromInvalidDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian lọc đến ngày không đúng dạng: ngày/tháng/năm.
        /// </summary>
        public static string DateToInvalidDataType {
            get {
                return ResourceManager.GetString("DateToInvalidDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa tất cả.
        /// </summary>
        public static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa ảnh.
        /// </summary>
        public static string DeletePhotos {
            get {
                return ResourceManager.GetString("DeletePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa lĩnh vực thành công..
        /// </summary>
        public static string DeleteTheFieldOfSuccess {
            get {
                return ResourceManager.GetString("DeleteTheFieldOfSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lược đồ.
        /// </summary>
        public static string Diagram {
            get {
                return ResourceManager.GetString("Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram.
        /// </summary>
        public static string DiagramEn {
            get {
                return ResourceManager.GetString("DiagramEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm tin văn bản.
        /// </summary>
        public static string DiemTinVanBan {
            get {
                return ResourceManager.GetString("DiemTinVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số hiệu văn bản.
        /// </summary>
        public static string DocNumber {
            get {
                return ResourceManager.GetString("DocNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VĂN BẢN LIÊN QUAN.
        /// </summary>
        public static string DocRelate {
            get {
                return ResourceManager.GetString("DocRelate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Anh.
        /// </summary>
        public static string DocsEnglish {
            get {
                return ResourceManager.GetString("DocsEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mới cập nhật.
        /// </summary>
        public static string DocsNewest {
            get {
                return ResourceManager.GetString("DocsNewest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại văn bản.
        /// </summary>
        public static string DocTypes {
            get {
                return ResourceManager.GetString("DocTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Văn bản UBND.
        /// </summary>
        public static string DocUBND {
            get {
                return ResourceManager.GetString("DocUBND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Văn bản trung ương liên quan.
        /// </summary>
        public static string DocUBNDLienQuan {
            get {
                return ResourceManager.GetString("DocUBNDLienQuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng văn bản.
        /// </summary>
        public static string DocumentFomat {
            get {
                return ResourceManager.GetString("DocumentFomat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải về.
        /// </summary>
        public static string DownLoad {
            get {
                return ResourceManager.GetString("DownLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string DownloadEn {
            get {
                return ResourceManager.GetString("DownloadEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa thông tin.
        /// </summary>
        public static string EditInformation {
            get {
                return ResourceManager.GetString("EditInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiệu lực.
        /// </summary>
        public static string Effect {
            get {
                return ResourceManager.GetString("Effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect.
        /// </summary>
        public static string EffectEn {
            get {
                return ResourceManager.GetString("EffectEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng hiệu lực.
        /// </summary>
        public static string EffectStatus {
            get {
                return ResourceManager.GetString("EffectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiệu lực.
        /// </summary>
        public static string EffectStatusMobile {
            get {
                return ResourceManager.GetString("EffectStatusMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không hợp lệ..
        /// </summary>
        public static string EmailRegularExpression {
            get {
                return ResourceManager.GetString("EmailRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập email nhận tin của bạn.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Anh.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Văn bản tiếng Anh.
        /// </summary>
        public static string EnglishDocument {
            get {
                return ResourceManager.GetString("EnglishDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã an toàn.
        /// </summary>
        public static string EnterTheSecurityCode {
            get {
                return ResourceManager.GetString("EnterTheSecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập nội dung văn bản cần tìm....
        /// </summary>
        public static string EnterWhatToFind {
            get {
                return ResourceManager.GetString("EnterWhatToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập email nhận tin của bạn.
        /// </summary>
        public static string EnterYourEmail {
            get {
                return ResourceManager.GetString("EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chính xác cụm từ.
        /// </summary>
        public static string ExactPhrase {
            get {
                return ResourceManager.GetString("ExactPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hết hiệu lực.
        /// </summary>
        public static string Expire {
            get {
                return ResourceManager.GetString("Expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng: ngày/tháng/năm.
        /// </summary>
        public static string FieldMustBeDate {
            get {
                return ResourceManager.GetString("FieldMustBeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lĩnh vực văn bản quan tâm.
        /// </summary>
        public static string FieldOfInterestDocument {
            get {
                return ResourceManager.GetString("FieldOfInterestDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Đăng ký để nhận được thông tin văn bản mới nhất về lĩnh vực bạn quan tâm..
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lĩnh vực tra cứu.
        /// </summary>
        public static string FieldSearch {
            get {
                return ResourceManager.GetString("FieldSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lĩnh vực hoạt động.
        /// </summary>
        public static string FieldWork {
            get {
                return ResourceManager.GetString("FieldWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lọc theo.
        /// </summary>
        public static string FilterBy {
            get {
                return ResourceManager.GetString("FilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm thấy.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string FirstAndLastName {
            get {
                return ResourceManager.GetString("FirstAndLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu điểm.
        /// </summary>
        public static string Focus {
            get {
                return ResourceManager.GetString("Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miễn phí.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dung lượng ảnh dưới 10Mb.
        /// </summary>
        public static string ImageSizeLessThan10Mb {
            get {
                return ResourceManager.GetString("ImageSizeLessThan10Mb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string JavascriptClose {
            get {
                return ResourceManager.GetString("JavascriptClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luật Việt Nam hỗ trợ các loại file sau: jpg , jpeg , png, gif.
        /// </summary>
        public static string JavascriptNoticeFileTypeSupport {
            get {
                return ResourceManager.GetString("JavascriptNoticeFileTypeSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghề nghiệp.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tham gia.
        /// </summary>
        public static string JoinDate {
            get {
                return ResourceManager.GetString("JoinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu Get Json không được phép.
        /// </summary>
        public static string JsonRequest_GetNotAllowed {
            get {
                return ResourceManager.GetString("JsonRequest_GetNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã biết.
        /// </summary>
        public static string Known {
            get {
                return ResourceManager.GetString("Known", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known.
        /// </summary>
        public static string KnownEn {
            get {
                return ResourceManager.GetString("KnownEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin pháp luật liên quan.
        /// </summary>
        public static string LegalNewsRelated {
            get {
                return ResourceManager.GetString("LegalNewsRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên kết cần biết.
        /// </summary>
        public static string LinkNeedToKnow {
            get {
                return ResourceManager.GetString("LinkNeedToKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách văn bản tiêu biểu.
        /// </summary>
        public static string ListOfTypicalText {
            get {
                return ResourceManager.GetString("ListOfTypicalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng đợi.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa phương.
        /// </summary>
        public static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập tài khoản.
        /// </summary>
        public static string LoginAccount {
            get {
                return ResourceManager.GetString("LoginAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập sử dụng dịch vụ.
        /// </summary>
        public static string LoginToUseTheService {
            get {
                return ResourceManager.GetString("LoginToUseTheService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm hiểu thêm.
        /// </summary>
        public static string LookingForMoreInformation {
            get {
                return ResourceManager.GetString("LookingForMoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tra cứu miễn phí.
        /// </summary>
        public static string LookUpForFree {
            get {
                return ResourceManager.GetString("LookUpForFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luật cần biết.
        /// </summary>
        public static string LuatCanBiet {
            get {
                return ResourceManager.GetString("LuatCanBiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn sử dụng.
        /// </summary>
        public static string ManualInstruction {
            get {
                return ResourceManager.GetString("ManualInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dung lượng ảnh vượt quá 2MB cho phép..
        /// </summary>
        public static string MaxFileSizeUpload {
            get {
                return ResourceManager.GetString("MaxFileSizeUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin nhắn.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string MsgContent {
            get {
                return ResourceManager.GetString("MsgContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Văn bản của tôi.
        /// </summary>
        public static string MyDocuments {
            get {
                return ResourceManager.GetString("MyDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin nhắn của tôi.
        /// </summary>
        public static string MyMessage {
            get {
                return ResourceManager.GetString("MyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công văn mới.
        /// </summary>
        public static string NewDispatch {
            get {
                return ResourceManager.GetString("NewDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VB mới.
        /// </summary>
        public static string NewDocuments {
            get {
                return ResourceManager.GetString("NewDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mới ban hành.
        /// </summary>
        public static string NewlyIssued {
            get {
                return ResourceManager.GetString("NewlyIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin vắn chính sách mới.
        /// </summary>
        public static string NewPolicyBriefs {
            get {
                return ResourceManager.GetString("NewPolicyBriefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản tin chỉ dành cho Khách hàng sử dụng gói tra cứu tiếng Anh hoặc Nâng cao.
        /// </summary>
        public static string NewsletterInfo {
            get {
                return ResourceManager.GetString("NewsletterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có văn bản.
        /// </summary>
        public static string NoDocumentsYet {
            get {
                return ResourceManager.GetString("NoDocumentsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Http Context.
        /// </summary>
        public static string NoHttpContext {
            get {
                return ResourceManager.GetString("NoHttpContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy văn bản phù hợp.
        /// </summary>
        public static string NoMatchingDocumentFound {
            get {
                return ResourceManager.GetString("NoMatchingDocumentFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Đây là tiện ích dành cho thành viên đăng ký dịch vụ&lt;/p&gt;&lt;em&gt;Quý khách vui lòng &lt;a href=&apos;#&apos; class=&apos;lawsVnLogin&apos; style=&apos;color: #a67942&apos; title=&apos;Đăng nhập tài khoản&apos;&gt;&lt;strong&gt;Đăng nhập&lt;/strong&gt;&lt;/a&gt; tài khoản LuatVietNam và &lt;a href=&apos;/dich-vu.html&apos; title=&apos;Đăng ký dịch vụ&apos;&gt;&lt;strong style=&apos;color: #a67942&apos;&gt;đăng ký sử dụng Dịch vụ tra cứu văn bản&lt;/strong&gt;&lt;/a&gt;.&lt;/em&gt;.
        /// </summary>
        public static string NoPermission {
            get {
                return ResourceManager.GetString("NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;This is a utility for members to sign up for the service.&lt;/p&gt;&lt;em&gt; Please &lt;a href=&apos;#&apos; class =&apos;lawsVnLogin&apos; style=&apos;color:# a67942&apos; title =&apos;Post enter your account&apos;&gt;&lt;strong&gt; Sign in &lt;/strong&gt;&lt;/a&gt; your LuatVietNam account and &lt;a href=&apos;/dich-vu.html&apos;home=&apos;Sign up for the service&apos;&gt;&lt;strong style= &apos;color:#a67942&apos;&gt; sign up for the text search service &lt;/strong&gt;&lt;/a&gt;.&lt;/em&gt;.
        /// </summary>
        public static string NoPermissionEn {
            get {
                return ResourceManager.GetString("NoPermissionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Đây là tiện ích dành cho thành viên đăng ký dịch vụ&lt;/p&gt;&lt;em&gt;Quý khách vui lòng &lt;a href=&apos;/dich-vu.html&apos; title=&apos;Đăng ký dịch vụ&apos;&gt;&lt;strong style=&apos;color: #a67942&apos;&gt;đăng ký sử dụng Dịch vụ tra cứu văn bản&lt;/strong&gt;&lt;/a&gt;.&lt;/em&gt;.
        /// </summary>
        public static string NoPermissionNotInRole {
            get {
                return ResourceManager.GetString("NoPermissionNotInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo hiệu lực.
        /// </summary>
        public static string NoticeOfValidity {
            get {
                return ResourceManager.GetString("NoticeOfValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Đây là tiện ích dành cho thành viên. &lt;/p&gt;&lt;em&gt;Quý khách vui lòng &lt;a href=&apos;#&apos; class=&apos;lawsVnLogin&apos; style=&apos;color: #a67942&apos; title=&apos;Đăng nhập tài khoản&apos;&gt;&lt;strong&gt;Đăng nhập&lt;/strong&gt;&lt;/a&gt; tài khoản LuatVietNam và &lt;a href=&apos;/dich-vu.html&apos; title=&apos;Đăng ký dịch vụ&apos;&gt;&lt;strong style=&apos;color: #a67942&apos;&gt;đăng ký sử dụng Dịch vụ tra cứu văn bản&lt;/strong&gt;&lt;/a&gt;.&lt;/em&gt;.
        /// </summary>
        public static string NotLoginMessage {
            get {
                return ResourceManager.GetString("NotLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Để xem mục Liên quan, hiểu các mối quan hệ, các văn bản liên quan đến văn bản đang xem.
        /// </summary>
        public static string NotPermissionDocRelate {
            get {
                return ResourceManager.GetString("NotPermissionDocRelate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Để xem tóm tắt thông báo.
        /// </summary>
        public static string NotPermissionDocSummary {
            get {
                return ResourceManager.GetString("NotPermissionDocSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cơ quan ban hành.
        /// </summary>
        public static string Organs {
            get {
                return ResourceManager.GetString("Organs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string OriginalDocument {
            get {
                return ResourceManager.GetString("OriginalDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lĩnh vực khác.
        /// </summary>
        public static string OtherField {
            get {
                return ResourceManager.GetString("OtherField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin pháp luật khác.
        /// </summary>
        public static string OtherLegalNews {
            get {
                return ResourceManager.GetString("OtherLegalNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các tin khác.
        /// </summary>
        public static string OtherNews {
            get {
                return ResourceManager.GetString("OtherNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gói.
        /// </summary>
        public static string package {
            get {
                return ResourceManager.GetString("package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu (*).
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chờ xử lý.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UBND các tỉnh.
        /// </summary>
        public static string PeoplesCommitteesOfProvinces {
            get {
                return ResourceManager.GetString("PeoplesCommitteesOfProvinces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cá nhân.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn lĩnh vực hoạt động của luật sư.
        /// </summary>
        public static string PleaseAelectTheFieldOfActivityOfTheLawyer {
            get {
                return ResourceManager.GetString("PleaseAelectTheFieldOfActivityOfTheLawyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn.
        /// </summary>
        public static string PleaseChoose {
            get {
                return ResourceManager.GetString("PleaseChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý khách vui lòng chọn ít nhất một lĩnh vực..
        /// </summary>
        public static string PleaseSelectAtLeastOneField {
            get {
                return ResourceManager.GetString("PleaseSelectAtLeastOneField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn một tỉnh quan tâm.
        /// </summary>
        public static string PleaseSelectAtLeastOneProvices {
            get {
                return ResourceManager.GetString("PleaseSelectAtLeastOneProvices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn lĩnh vực.
        /// </summary>
        public static string PleaseSelectTheField {
            get {
                return ResourceManager.GetString("PleaseSelectTheField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qúy  khách vui lòng thử lại sau..
        /// </summary>
        public static string PleaseTryAgainLater {
            get {
                return ResourceManager.GetString("PleaseTryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban hành.
        /// </summary>
        public static string Promulgate {
            get {
                return ResourceManager.GetString("Promulgate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promulgate.
        /// </summary>
        public static string PromulgateEn {
            get {
                return ResourceManager.GetString("PromulgateEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuộc tính.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh/Thành phố.
        /// </summary>
        public static string ProvinceCity {
            get {
                return ResourceManager.GetString("ProvinceCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh/Tp quan tâm.
        /// </summary>
        public static string ProvinceOfInterestDocument {
            get {
                return ResourceManager.GetString("ProvinceOfInterestDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận bản tin hàng tuần qua Email.
        /// </summary>
        public static string ReceiveWeeklyNewslettersByEmail {
            get {
                return ResourceManager.GetString("ReceiveWeeklyNewslettersByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký giao diện cá nhân.
        /// </summary>
        public static string RegisterAPersonalInterface {
            get {
                return ResourceManager.GetString("RegisterAPersonalInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký dùng thử dịch vụ miễn phí.
        /// </summary>
        public static string RegisterForTrialService {
            get {
                return ResourceManager.GetString("RegisterForTrialService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký ngay.
        /// </summary>
        public static string RegisterNow {
            get {
                return ResourceManager.GetString("RegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký sử dụng dịch vụ.
        /// </summary>
        public static string RegisterToUseTheService {
            get {
                return ResourceManager.GetString("RegisterToUseTheService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VB liên quan.
        /// </summary>
        public static string Relate {
            get {
                return ResourceManager.GetString("Relate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên quan.
        /// </summary>
        public static string Relate2 {
            get {
                return ResourceManager.GetString("Relate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu chuẩn liên quan.
        /// </summary>
        public static string RelatedStandards {
            get {
                return ResourceManager.GetString("RelatedStandards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relate.
        /// </summary>
        public static string RelateEn {
            get {
                return ResourceManager.GetString("RelateEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi nhớ.
        /// </summary>
        public static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gia hạn dịch vụ.
        /// </summary>
        public static string RenewalOfService {
            get {
                return ResourceManager.GetString("RenewalOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to văn bản.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại.
        /// </summary>
        public static string Retype {
            get {
                return ResourceManager.GetString("Retype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu vào văn bản của tôi.
        /// </summary>
        public static string SaveDocumentOfInterest {
            get {
                return ResourceManager.GetString("SaveDocumentOfInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save into my documents.
        /// </summary>
        public static string SaveDocumentOfInterestEn {
            get {
                return ResourceManager.GetString("SaveDocumentOfInterestEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÌM VĂN BẢN PHÁP LUẬT VIỆT NAM.
        /// </summary>
        public static string SearchForDocumentsOnVietnameseLaw {
            get {
                return ResourceManager.GetString("SearchForDocumentsOnVietnameseLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập nội dung cần tìm .
        /// </summary>
        public static string SearchKeywords {
            get {
                return ResourceManager.GetString("SearchKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý khách vui lòng nhập từ khóa tìm kiếm.
        /// </summary>
        public static string SearchKeywordsRequired {
            get {
                return ResourceManager.GetString("SearchKeywordsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải từ máy tính.
        /// </summary>
        public static string SelectAPhotoFromYourComputer {
            get {
                return ResourceManager.GetString("SelectAPhotoFromYourComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt mật khẩu mới.
        /// </summary>
        public static string SetANewPassword {
            get {
                return ResourceManager.GetString("SetANewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gắn sao cho tin nhắn thành công..
        /// </summary>
        public static string SetstarTheMessageForSuccess {
            get {
                return ResourceManager.GetString("SetstarTheMessageForSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người ký.
        /// </summary>
        public static string Signers {
            get {
                return ResourceManager.GetString("Signers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thành viên.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký nhận tin văn bản mới.
        /// </summary>
        public static string SignUpForANewLetterEmail {
            get {
                return ResourceManager.GetString("SignUpForANewLetterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký để nhận được thông tin văn bản mới nhất về lĩnh vực bạn quan tâm.
        /// </summary>
        public static string SignUpToReceiveTheLatestDocumentInformationAboutYourAreaOfInterest {
            get {
                return ResourceManager.GetString("SignUpToReceiveTheLatestDocumentInformationAboutYourAreaOfInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bao gồm từ {2} ký tự trở lên..
        /// </summary>
        public static string StringLengthConfirmPassword {
            get {
                return ResourceManager.GetString("StringLengthConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bao gồm từ {2} ký tự trở lên..
        /// </summary>
        public static string StringLengthPassword {
            get {
                return ResourceManager.GetString("StringLengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thông báo hiệu lực.
        /// </summary>
        public static string SubscriptionNoticeOfValidity {
            get {
                return ResourceManager.GetString("SubscriptionNoticeOfValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thông báo hiệu lực thành công..
        /// </summary>
        public static string SubscriptionNoticeOfValiditySuccessful {
            get {
                return ResourceManager.GetString("SubscriptionNoticeOfValiditySuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin doanh nghiệp thành công.
        /// </summary>
        public static string SuccessfulBusinessInformationUpdates {
            get {
                return ResourceManager.GetString("SuccessfulBusinessInformationUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tóm tắt.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string SummaryEn {
            get {
                return ResourceManager.GetString("SummaryEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế.
        /// </summary>
        public static string TaxCode {
            get {
                return ResourceManager.GetString("TaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VB được hợp nhất.
        /// </summary>
        public static string TheDocumentIsMerged {
            get {
                return ResourceManager.GetString("TheDocumentIsMerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả đang lọc theo.
        /// </summary>
        public static string TheResultsAreFilteredBy {
            get {
                return ResourceManager.GetString("TheResultsAreFilteredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã an toàn không đúng.
        /// </summary>
        public static string TheSecurityCodeIsIncorrect {
            get {
                return ResourceManager.GetString("TheSecurityCodeIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đây là tiện ích dành cho thành viên đăng ký dịch vụ.
        /// </summary>
        public static string ThisIsAUtilityForMembersWhoSignUpForTheService {
            get {
                return ResourceManager.GetString("ThisIsAUtilityForMembersWhoSignUpForTheService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin pháp luật.
        /// </summary>
        public static string TinPhapLuat {
            get {
                return ResourceManager.GetString("TinPhapLuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ đề.
        /// </summary>
        public static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử giao dịch.
        /// </summary>
        public static string TransactionHistory {
            get {
                return ResourceManager.GetString("TransactionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dùng thử dịch vụ thuê bao trong 15 ngày.
        /// </summary>
        public static string TrySubscriptionServiceFor15Days {
            get {
                return ResourceManager.GetString("TrySubscriptionServiceFor15Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rất tiếc. Quý khách không xem được nội dung này. Vui lòng đăng nhập tài khoản hoặc liên hệ với quản trị website để biết thêm chi tiết..
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Văn bản hợp nhất.
        /// </summary>
        public static string UnifiedText {
            get {
                return ResourceManager.GetString("UnifiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đơn vị.
        /// </summary>
        public static string UnitName {
            get {
                return ResourceManager.GetString("UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bỏ gắn sao cho tin nhắn thành công..
        /// </summary>
        public static string UnstarTheMessageForSuccess {
            get {
                return ResourceManager.GetString("UnstarTheMessageForSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thành công.
        /// </summary>
        public static string UnSuccess {
            get {
                return ResourceManager.GetString("UnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật tỉnh/tp quan tâm thành công.
        /// </summary>
        public static string UpdateProvinceOfSuccess {
            get {
                return ResourceManager.GetString("UpdateProvinceOfSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin tài khoản thành công.
        /// </summary>
        public static string UpdateSuccessfulAccountInformation {
            get {
                return ResourceManager.GetString("UpdateSuccessfulAccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật lĩnh vực thành công..
        /// </summary>
        public static string UpdateTheFieldOfSuccess {
            get {
                return ResourceManager.GetString("UpdateTheFieldOfSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang cập nhật.
        /// </summary>
        public static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu phù hợp..
        /// </summary>
        public static string UpdatingData {
            get {
                return ResourceManager.GetString("UpdatingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating.
        /// </summary>
        public static string UpdatingEn {
            get {
                return ResourceManager.GetString("UpdatingEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nâng cấp và gia hạn dịch vụ.
        /// </summary>
        public static string UpgradeAndRenewService {
            get {
                return ResourceManager.GetString("UpgradeAndRenewService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải ảnh đại diện.
        /// </summary>
        public static string UploadARepresentativeImage {
            get {
                return ResourceManager.GetString("UploadARepresentativeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập (*).
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang dùng dịch vụ.
        /// </summary>
        public static string UsingTheService {
            get {
                return ResourceManager.GetString("UsingTheService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu chuẩn XDVN.
        /// </summary>
        public static string VietNamConstruct {
            get {
                return ResourceManager.GetString("VietNamConstruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu chuẩn ngành.
        /// </summary>
        public static string VietNamDepartment {
            get {
                return ResourceManager.GetString("VietNamDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        public static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt và tiếng Anh.
        /// </summary>
        public static string VietnameseAndEnglish {
            get {
                return ResourceManager.GetString("VietnameseAndEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Văn bản tiếng Việt.
        /// </summary>
        public static string VietnameseDocument {
            get {
                return ResourceManager.GetString("VietnameseDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        public static string VietnameseEn {
            get {
                return ResourceManager.GetString("VietnameseEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quy chuẩn Việt Nam.
        /// </summary>
        public static string VietNamRegulations {
            get {
                return ResourceManager.GetString("VietNamRegulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu chuẩn Việt Nam.
        /// </summary>
        public static string VietNamStandard {
            get {
                return ResourceManager.GetString("VietNamStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý khách quan tâm đến dịch vụ nào?.
        /// </summary>
        public static string WhatServiceAreYouInterestedIn {
            get {
                return ResourceManager.GetString("WhatServiceAreYouInterestedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tại sao chọn LuatVietnam.vn?.
        /// </summary>
        public static string WhyChooseLuatVietnam {
            get {
                return ResourceManager.GetString("WhyChooseLuatVietnam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm ban hành.
        /// </summary>
        public static string YearIssued {
            get {
                return ResourceManager.GetString("YearIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có tài khoản.
        /// </summary>
        public static string YouDoNotHaveAnAccount {
            get {
                return ResourceManager.GetString("YouDoNotHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã an toàn của bạn.
        /// </summary>
        public static string YourSecurityCode {
            get {
                return ResourceManager.GetString("YourSecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý khách đăng ký nhận bản tin thành công.
        /// </summary>
        public static string YouSignupForASuccessfulNewsletter {
            get {
                return ResourceManager.GetString("YouSignupForASuccessfulNewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn xóa lĩnh vực này?.
        /// </summary>
        public static string YouWantToDeleteThisField {
            get {
                return ResourceManager.GetString("YouWantToDeleteThisField", resourceCulture);
            }
        }
    }
}
