//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawsVN.FileUploadService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileUploadService.FileUploaderSoap")]
    public interface FileUploaderSoap {
        
        // CODEGEN: Generating message contract since element name buffer from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        LawsVN.FileUploadService.UploadFileResponse UploadFile(LawsVN.FileUploadService.UploadFileRequest request);
        
        // CODEGEN: Generating message contract since element name buffer from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LawyersUploadFile", ReplyAction="*")]
        LawsVN.FileUploadService.LawyersUploadFileResponse LawyersUploadFile(LawsVN.FileUploadService.LawyersUploadFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFile", Namespace="http://tempuri.org/", Order=0)]
        public LawsVN.FileUploadService.UploadFileRequestBody Body;
        
        public UploadFileRequest() {
        }
        
        public UploadFileRequest(LawsVN.FileUploadService.UploadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] buffer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string appKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool createImageThumbnail;
        
        public UploadFileRequestBody() {
        }
        
        public UploadFileRequestBody(byte[] buffer, string fileName, string appKey, bool createImageThumbnail) {
            this.buffer = buffer;
            this.fileName = fileName;
            this.appKey = appKey;
            this.createImageThumbnail = createImageThumbnail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public LawsVN.FileUploadService.UploadFileResponseBody Body;
        
        public UploadFileResponse() {
        }
        
        public UploadFileResponse(LawsVN.FileUploadService.UploadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadFileResult;
        
        public UploadFileResponseBody() {
        }
        
        public UploadFileResponseBody(string UploadFileResult) {
            this.UploadFileResult = UploadFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LawyersUploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LawyersUploadFile", Namespace="http://tempuri.org/", Order=0)]
        public LawsVN.FileUploadService.LawyersUploadFileRequestBody Body;
        
        public LawyersUploadFileRequest() {
        }
        
        public LawyersUploadFileRequest(LawsVN.FileUploadService.LawyersUploadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LawyersUploadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] buffer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lawsId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string directory;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string appKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool createImageThumbnail;
        
        public LawyersUploadFileRequestBody() {
        }
        
        public LawyersUploadFileRequestBody(byte[] buffer, string fileName, string lawsId, string directory, string appKey, bool createImageThumbnail) {
            this.buffer = buffer;
            this.fileName = fileName;
            this.lawsId = lawsId;
            this.directory = directory;
            this.appKey = appKey;
            this.createImageThumbnail = createImageThumbnail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LawyersUploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LawyersUploadFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public LawsVN.FileUploadService.LawyersUploadFileResponseBody Body;
        
        public LawyersUploadFileResponse() {
        }
        
        public LawyersUploadFileResponse(LawsVN.FileUploadService.LawyersUploadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LawyersUploadFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LawyersUploadFileResult;
        
        public LawyersUploadFileResponseBody() {
        }
        
        public LawyersUploadFileResponseBody(string LawyersUploadFileResult) {
            this.LawyersUploadFileResult = LawyersUploadFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileUploaderSoapChannel : LawsVN.FileUploadService.FileUploaderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileUploaderSoapClient : System.ServiceModel.ClientBase<LawsVN.FileUploadService.FileUploaderSoap>, LawsVN.FileUploadService.FileUploaderSoap {
        
        public FileUploaderSoapClient() {
        }
        
        public FileUploaderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileUploaderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileUploaderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileUploaderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LawsVN.FileUploadService.UploadFileResponse LawsVN.FileUploadService.FileUploaderSoap.UploadFile(LawsVN.FileUploadService.UploadFileRequest request) {
            return base.Channel.UploadFile(request);
        }
        
        public string UploadFile(byte[] buffer, string fileName, string appKey, bool createImageThumbnail) {
            LawsVN.FileUploadService.UploadFileRequest inValue = new LawsVN.FileUploadService.UploadFileRequest();
            inValue.Body = new LawsVN.FileUploadService.UploadFileRequestBody();
            inValue.Body.buffer = buffer;
            inValue.Body.fileName = fileName;
            inValue.Body.appKey = appKey;
            inValue.Body.createImageThumbnail = createImageThumbnail;
            LawsVN.FileUploadService.UploadFileResponse retVal = ((LawsVN.FileUploadService.FileUploaderSoap)(this)).UploadFile(inValue);
            return retVal.Body.UploadFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LawsVN.FileUploadService.LawyersUploadFileResponse LawsVN.FileUploadService.FileUploaderSoap.LawyersUploadFile(LawsVN.FileUploadService.LawyersUploadFileRequest request) {
            return base.Channel.LawyersUploadFile(request);
        }
        
        public string LawyersUploadFile(byte[] buffer, string fileName, string lawsId, string directory, string appKey, bool createImageThumbnail) {
            LawsVN.FileUploadService.LawyersUploadFileRequest inValue = new LawsVN.FileUploadService.LawyersUploadFileRequest();
            inValue.Body = new LawsVN.FileUploadService.LawyersUploadFileRequestBody();
            inValue.Body.buffer = buffer;
            inValue.Body.fileName = fileName;
            inValue.Body.lawsId = lawsId;
            inValue.Body.directory = directory;
            inValue.Body.appKey = appKey;
            inValue.Body.createImageThumbnail = createImageThumbnail;
            LawsVN.FileUploadService.LawyersUploadFileResponse retVal = ((LawsVN.FileUploadService.FileUploaderSoap)(this)).LawyersUploadFile(inValue);
            return retVal.Body.LawyersUploadFileResult;
        }
    }
}
